{
 "title": "EMQX Energy Storage",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Stored energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"remainingCapacity\")\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Input power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"inputPower\")\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")\n  |> yield(name: \"inputPower\")"
    }
   ]
  },
  {
   "title": "Output power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outputPower\")\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")\n  |> yield(name: \"outputPower\")"
    }
   ]
  },
  {
   "title": "AVG voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")\n  |> yield(name: \"voltage\")"
    }
   ]
  },
  {
   "title": "AVG temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Energy change log",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"deltaCapacity\")\n  |> group(columns: [\"id\"])\n  |> map(fn: (r) => ({\n      name: r._name,\n      energyChange: r._value,\n      _time: r._time\n    })\n  )\n"
    }
   ]
  },
  {
   "title": "Stored energy log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"remainingCapacity\")\n  |> group(columns: [\"id\"])\n  |> map(fn: (r) => ({\n      name: r._name,\n      storedEnergy: r._value,\n      _time: r._time\n    })\n  )\n"
    },
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"inputPower\")\n  |> group(columns: [\"id\"])\n  |> map(fn: (r) => ({\n      name: r._name,\n      inputPower: r._value,\n      _time: r._time\n    })\n  )\n"
    },
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outputPower\")\n  |> group(columns: [\"id\"])\n  |> map(fn: (r) => ({\n      name: r._name,\n      outputPower: r._value,\n      _time: r._time\n    })\n  )\n"
    }
   ]
  }
 ]
}